### PR TITLE
Compiling issue with relative path name

### PR DESCRIPTION
**Pull request by maxscott**
I had an issue with "rake db:run" that begins:
ActionView::Template::Error: require_tree argument must be a relative path
  (in /home/max/Code/potlucky/spec/javascripts/spec_helper.js.coffee:5)
This change resolved that issue for me. Thanks for the great project!

### CODE REVIEW

**Comment by pseudomuto** [comment]
I had this same issue...:+1: for the fix!

**Comment by maxscott** [comment]
Glad (sortof) I wasn't the only one! Thought I was taking crazy pills there for a little while.. :ambulance:

**Comment by kristianmandrup** [comment]
Released version v0.2.0. with latest fixes merged and a new `Ember::ResourceController`

**Comment by johnnyshields** [comment]
:+1: thanks!

**Comment by pseudomuto** [comment]
Nice! :+1:

**Pull request merged**
